### ISSUE TITLE
Rogue bee

### ISSUE THREAD

**Issue by bellabie** [ncase/bees#8]
Sometimes (maybe caused by clicks or collisions) the player bee goes out of control and rapidly waggles off screen never to be seen again.

**Comment by gqln** [comment]
Fixed this in the last commit, I'm pretty sure.
One small issue was that both canvases had the id "canvas", so every other reported mouse position would be garbage. The main issue was: when the bee was returning from the left side of the canvas, its destination angle would not converge.

**Comment by bellabie** [comment]
Ah, nice, @gqln! I was wondering why it was always going rogue in the same direction. I'll consider this closed, but let's keep an eye on it.
